[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
optimize = true
optimizer_runs = 5000000
via-ir = true
verbosity = 5
fs_permissions = [{ access = "read-write", path = "./" }]

[fuzz]
runs = 1000

[rpc_endpoints]
goerli = "${RPC_GOERLI}"
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${ETHERSCAN_API_KEY}" }
